ALTER TABLE {{ .Activities }} MODIFY COLUMN `attributes` MEDIUMBLOB NOT NULL;
ALTER TABLE {{ .History }} MODIFY COLUMN `attributes` MEDIUMBLOB NOT NULL;
ALTER TABLE {{ .PendingEvents }} MODIFY COLUMN `attributes` MEDIUMBLOB NOT NULL;
